#!/bin/sh
#//
#// $Id: buildsettings_posix_TEMPLATE 1417 2015-08-03 14:31:38Z bloehr $
#//
#// DESCRIPTION   TRDP build settings for posix target
#//
#// AUTHOR         Christoph Schneider, Bombardier Transportation GmbH
#//
#// All rights reserved. Reproduction, modification, use or disclosure
#// to third parties without express authority is forbidden.
#// Copyright Bombardier Transportation GmbH, Germany, 2013.
#//
export DOXYPATH="/usr/local/bin/"
unset INCPATH
