#!/bin/sh
# Automatically copy firmware on SD-Card to internal flash when booting from SD.
#  
# Progress displayed via LED's U1 to U4 
# YELLOW: Copy process is active
# GREEN: Successful done!
# RED: Finished with ERROR!
#
# Symbolic link in /etc/rc.d/ automatically removed on first boot from internal flash.


PATH=/usr/bin:/usr/sbin:/bin:/sbin
CFGPATH=/etc/config-tools
RCLINK=/etc/rc.d/S95_cpsd2intern

leds_off()
{
    eventmsg 0x40010000
    eventmsg 0x40010100
    eventmsg 0x40010200
    eventmsg 0x40010300
}

leds_green()
{
    eventmsg 0x40010001
    eventmsg 0x40010101
    eventmsg 0x40010201
    eventmsg 0x40010301
}

leds_red()
{
    eventmsg 0x40010002
    eventmsg 0x40010102
    eventmsg 0x40010202
    eventmsg 0x40010302
}

leds_yellow()
{
    eventmsg 0x40010003
    eventmsg 0x40010103
    eventmsg 0x40010203
    eventmsg 0x40010303
}

case $1 in
    start)
        bootmedia=$($CFGPATH/get_filesystem_data active-partition-medium)
        if [ "$bootmedia" = "sd-card" ]; then
            echo "Copy SD card to internal flash. Takes a while ..."
            echo "Finished when LED's U1 to U4 are lit green"
            leds_yellow
            $CFGPATH/copy_firmware_image source-medium=sd-card destination-medium=internal-flash &> /dev/null
            if [ "$?" -eq "0" ]; then
                leds_green
                echo "Done"
            else
                leds_red
                echo "Error occured"
                . $CFGPATH/config_tool_defines
                if [ -f $LAST_ERROR_FILENAME ]; then
                    cat $LAST_ERROR_FILENAME;
                    rm $LAST_ERROR_FILENAME
                fi
            fi
        else
            rm -f $RCLINK
        fi
        ;;

    *)
        echo "Usage: ${0} start"
        exit 1
        ;;
esac
