##----------------------------------------------------------------------------------------------------------------------
### Copyright (c) WAGO Kontakttechnik GmbH & Co. KG
###
### PROPRIETARY RIGHTS of WAGO Kontakttechnik GmbH & Co. KG are involved in
### the subject matter of this material. All manufacturing, reproduction,
### use, and sales rights pertaining to this subject matter are governed
### by the license agreement. The recipient of this software implicitly
### accepts the terms of the license.
###
##----------------------------------------------------------------------------------------------------------------------
##----------------------------------------------------------------------------------------------------------------------
###
###  \file     Makefile
###
###  \version  
###
###  \brief    Makefile for example applications using liboms
###
###  \author   Thomas Brandt : WAGO Kontakttechnik GmbH & Co. KG
##----------------------------------------------------------------------------------------------------------------------

CFLAGS += -O2 -g -Wall 
CPPFLAGS +=
LDFLAGS += -llibloader -loms -ldl

all: omsreader  

clean:
	-rm -f omsreader 

install:

.PHONY: all clean install

